version: '3.1'

services:

  mariadb:
    image: mariadb:10.4.7
    restart: always
    container_name: mariadb
    ports:
      # 端口映射
      - 3306:3306
    volumes:
      # 容器与宿主机时间同步
      - /etc/localtime:/etc/localtime
      # 数据库目录映射
      - ./config/data/mariadb:/var/lib/mysql
      # （不推荐）数据库配置文件映射（如果需要自己配置的话打开--他会覆盖docker容器中的配置文件夹-如果是空文件夹那么会把容器内的配置文件全都替换成空）
      #- ./config/data/mariadb-config/my.cnf:/etc/mysql/my.cnf
      # （推荐）如果要使用自定义的MySQL配置，则可以在主机上的目录中创建备用配置文件，然后将该目录位置/etc/mysql/conf.d安装在mariadb容器内。自己所需的配置文件可以放在自己服务器./config/data/mariadb-config里面，
      - ./config/data/mariadb-config:/etc/mysql/conf.d
    environment:
      TIME_ZONE: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: adsladsl
      MYSQL_USER: test   #创建test用户
      MYSQL_PASSWORD: test  #设置test用户的密码